### ISSUE TITLE
Wireframe Design

### ISSUE THREAD

**Issue by TashUni** [Cos301/Clockwise#1]

**Comment by ghost** [comment]
[Chat_LoFi.pdf](https://github.com/Cos301/Clockwise/files/11319275/Chat_LoFi.pdf)

**Comment by ghost** [comment]
[Explore_Feed_LoFi.pdf](https://github.com/Cos301/Clockwise/files/11319289/Explore_Feed_LoFi.pdf)

**Comment by ghost** [comment]
[Post_LoFi.pdf](https://github.com/Cos301/Clockwise/files/11319296/Post_LoFi.pdf)

**Comment by ghost** [comment]
[Profile_LoFi.pdf](https://github.com/Cos301/Clockwise/files/11319298/Profile_LoFi.pdf)

**Comment by ghost** [comment]
[LoFi_Prototype_GroupSuggestions.docx](https://github.com/Cos301/Clockwise/files/11319305/LoFi_Prototype_GroupSuggestions.docx)

**Comment by ghost** [comment]
[Chat_LoFi_2.pdf](https://github.com/Cos301/Clockwise/files/11319311/Chat_LoFi_2.pdf)

**Comment by ghost** [comment]
[Explore_Feed_LoFi_2.pdf](https://github.com/Cos301/Clockwise/files/11319317/Explore_Feed_LoFi_2.pdf)

**Comment by ghost** [comment]
[Login_Signup_LoFi.pdf](https://github.com/Cos301/Clockwise/files/11319318/Login_Signup_LoFi.pdf)

**Comment by ghost** [comment]
[Post_LoFi_2.pdf](https://github.com/Cos301/Clockwise/files/11319319/Post_LoFi_2.pdf)

**Comment by ghost** [comment]
[Profile_LoFi_2.pdf](https://github.com/Cos301/Clockwise/files/11319321/Profile_LoFi_2.pdf)

**Comment by ghost** [comment]
[Chat_HiFi.pdf](https://github.com/Cos301/Clockwise/files/11319322/Chat_HiFi.pdf)

**Comment by ghost** [comment]
[Explore_Feed_HiFi.pdf](https://github.com/Cos301/Clockwise/files/11319326/Explore_Feed_HiFi.pdf)

**Comment by ghost** [comment]
[Login_Signup_HiFi.pdf](https://github.com/Cos301/Clockwise/files/11319329/Login_Signup_HiFi.pdf)

**Comment by ghost** [comment]
[Post_HiFi.pdf](https://github.com/Cos301/Clockwise/files/11319332/Post_HiFi.pdf)

**Comment by ghost** [comment]
[Profile_HiFi.pdf](https://github.com/Cos301/Clockwise/files/11319334/Profile_HiFi.pdf)
